In [1]:
import psycopg2
import pandas as pd
import numpy as np
import datetime as dt
from sqlalchemy import create_engine
import time

In [61]:
# Conexión a la base de datos
conn = psycopg2.connect(
    host="dpg-cf3enqun6mplnpe950v0-a.oregon-postgres.render.com",
    database="olist",
    user="olist",
    password="IHCRtcefMFbJIjUMXuUMtcIfpTAEo5d1"
)

In [3]:
# Carga actual
engine = create_engine('postgresql://olist:IHCRtcefMFbJIjUMXuUMtcIfpTAEo5d1@dpg-cf3enqun6mplnpe950v0-a.oregon-postgres.render.com:5432/olist')

product_cat_name_ac = pd.read_sql_table('product_category_name_translation', engine)
geolocation_ac = pd.read_sql_table('geolocation', engine)
marketing_ac = pd.read_sql_table('marketing_qualified_leads', engine)
closed_deals_ac = pd.read_sql_table('closed_deals', engine)
sellers_ac = pd.read_sql_table('olist_sellers', engine)
customers_ac=pd.read_sql_table('customers', engine)
orders_ac = pd.read_sql_table('orders', engine)
payments_ac = pd.read_sql_table('order_payments', engine)
reviews_ac = pd.read_sql_table('order_reviews', engine)
products_ac = pd.read_sql_table('products', engine)
items_ac = pd.read_sql_table('order_items', engine)

engine.dispose()

In [36]:
#Carga incremental crudo
product_cat_name_inc=pd.read_csv("Datasetsincremental/product_category_name_translation.csv")
geolocation_inc=pd.read_csv("Datasetsincremental/olist_geolocation_dataset.csv", dtype= {'geolocation_zip_code_prefix': str})
marketing_inc=pd.read_csv("Datasetsincremental/olist_marketing_qualified_leads_dataset.csv")
closed_deals_inc=pd.read_csv("Datasetsincremental/olist_closed_deals_dataset.csv")
sellers_inc=pd.read_csv("Datasetsincremental/olist_sellers_dataset.csv",dtype={"seller_zip_code_prefix": str})
customers_inc=pd.read_csv("Datasetsincremental/olist_customers_dataset.csv",dtype={"customer_zip_code_prefix": str})
orders_inc=pd.read_csv("Datasetsincremental/olist_orders_dataset.csv")
payments_inc=pd.read_csv("Datasetsincremental/olist_order_payments_dataset.csv")
reviews_inc=pd.read_csv("Datasetsincremental/olist_order_reviews_dataset.csv")
products_inc=pd.read_csv("Datasetsincremental/olist_products_dataset.csv")
items_inc=pd.read_csv("Datasetsincremental/olist_order_items_dataset.csv")
df_coord_estados_inc = pd.read_csv('datasetsincremental/coordenadas_estados.csv',sep=';')
df_coord_ciudades_inc = pd.read_csv('datasetsincremental/coordenadas_ciudades.csv')
br_info_inc = pd.read_csv('datasetsincremental/br_info.csv')

In [38]:
#Product Category Name Translation

def etl_product_cat():
    product_cat_name=product_cat_name_inc.copy()

    product_cat_name=product_cat_name.append({"product_category_name" : "pc_gamer" , "product_category_name_english" : "pc_gamer"} , ignore_index=True)
    product_cat_name=product_cat_name.append({"product_category_name" : "portateis_cozinha_e_preparadores_de_alimentos" , "product_category_name_english" : "kitchen_and_food_preparation_racks"} , ignore_index=True)
    product_cat_name["product_category_name"]=product_cat_name["product_category_name"].str.replace("_"," ")
    product_cat_name["product_category_name_english"]=product_cat_name["product_category_name_english"].str.replace("_"," ")

    return product_cat_name

# Geolocation

def etl_geolocation():

    df_coord_estados = df_coord_estados_inc.copy()
    df_coord_ciudades = df_coord_ciudades_inc.copy()
    br_info = br_info_inc.copy()
    geolocation=geolocation_inc.copy()
    sellers=sellers_inc.copy()
    customers=customers_inc.copy()

    # Renombre de columnas

    geolocation.rename(columns={'geolocation_zip_code_prefix': 'zip_code_prefix','geolocation_city': 'city','geolocation_state': 'state'}, inplace=True)
    sellers.rename(columns={'seller_zip_code_prefix': 'zip_code_prefix', 'seller_city': 'city', 'seller_state': 'state'}, inplace=True)
    customers.rename(columns={'customer_zip_code_prefix': 'zip_code_prefix', 'customer_city': 'city', 'customer_state': 'state'}, inplace=True)

    # Concatención
    # Concateno todos los datasets
    df_concat = pd.concat([geolocation,sellers[['zip_code_prefix','city','state']],customers[['zip_code_prefix','city','state']]],axis=0)

    # PROCESAMIENTO
    df_procesado = df_concat.groupby(by='zip_code_prefix', as_index=False).min()
    df_procesado = df_procesado.merge(br_info, how='left', left_on='state', right_on='sigla')
    # Renombre
    df_procesado.rename(columns={'id': 'id_state', 'state':'state_sigla','nome':'state_name','nome_regiao':'region_name'}, inplace=True)
    # Drop de sigla
    df_procesado.drop(columns=['sigla'],inplace=True)
    # Reordenado
    df_procesado = df_procesado[['zip_code_prefix','region_name','id_state','state_sigla','state_name','city','geolocation_lat','geolocation_lng']]
    # Añado columna localizador
    df_procesado['localizador'] = df_procesado['city'] + ' ' + df_procesado['state_sigla'] + ', Brazil'
    # Merge con coordenadas de city y estados
    df_procesado = df_procesado.merge(df_coord_ciudades[['localizador','latitud','longitud']], on = 'localizador')
    df_procesado = df_procesado.merge(df_coord_estados, how='left', left_on='state_sigla', right_on='uf')
    # Renombre columnas
    df_procesado.rename(columns={'latitud': 'latitud_city','longitud': 'longitud_city','latitude': 'latitud_state', 'longitude':'longitud_state'}, inplace=True)
    # Elimino geolocation_latitude y geolocation_longitude y uf
    df_final_procesado = df_procesado.drop(columns=['uf','geolocation_lat','geolocation_lng'])

    return df_final_procesado 

# Marketing

def etl_marketing():
    marketing=marketing_inc.copy()

    marketing.drop(columns=["landing_page_id"],axis=1,inplace=True)

    marketing["first_contact_date"]=pd.to_datetime(marketing["first_contact_date"],format="%Y-%m-%d %H:%M:%S")

    marketing.fillna("SIN DATO",inplace=True)
    return marketing

# Sellers

def etl_sellers():
    
    sellers=sellers_inc.copy()
    closed_deals=closed_deals_inc.copy()

    sellers.drop(columns=["seller_city","seller_state"],axis=1,inplace=True)

    return sellers

# Closed Deals

def etl_closed_deals():
    closed_deals=closed_deals_inc.copy()

    closed_deals.drop(columns=["sdr_id","sr_id","lead_behaviour_profile","has_company","has_gtin","average_stock","business_type","declared_product_catalog_size","declared_monthly_revenue"],axis=1,inplace=True)
    closed_deals["won_date"]=pd.to_datetime(closed_deals["won_date"],format="%Y-%m-%d %H:%M:%S")
    closed_deals.fillna("SIN DATO",inplace=True)
    
    return closed_deals


# Customers

def etl_customers():
    customers=customers_inc.copy()

    customers.drop(columns=["customer_city","customer_state"],axis=1,inplace=True)

    return customers

# Orders

def etl_orders():

    payments=payments_inc.copy()
    orders=orders_inc.copy()
    
    orders["order_purchase_timestamp"]=pd.to_datetime(orders["order_purchase_timestamp"],format="%Y-%m-%d %H:%M:%S")
    orders["order_approved_at"]=pd.to_datetime(orders["order_approved_at"],format="%Y-%m-%d %H:%M:%S")
    orders["order_delivered_carrier_date"]=pd.to_datetime(orders["order_delivered_carrier_date"],format="%Y-%m-%d %H:%M:%S")
    orders["order_delivered_customer_date"]=pd.to_datetime(orders["order_delivered_customer_date"],format="%Y-%m-%d %H:%M:%S")
    orders["order_estimated_delivery_date"]=pd.to_datetime(orders["order_estimated_delivery_date"],format="%Y-%m-%d %H:%M:%S")

    orders['difference_days1'] = orders['order_approved_at'] - orders['order_purchase_timestamp']
    orders['difference_days2'] = orders['order_delivered_carrier_date'] - orders['order_approved_at']
    orders['difference_days3'] = orders['order_delivered_customer_date'] - orders['order_approved_at']
    orders['difference_days4'] = orders['order_delivered_customer_date'] - orders['order_delivered_carrier_date']
    orders['difference_days5'] = orders['order_estimated_delivery_date'] - orders['order_delivered_customer_date']

    orders["order_approved_at_new"]=orders["order_purchase_timestamp"]+(orders["order_delivered_carrier_date"]-orders["order_purchase_timestamp"])/2

    orders.loc[(orders["difference_days2"]<pd.Timedelta(0)) & (orders["difference_days3"]<pd.Timedelta(0)),"order_approved_at"]=orders.loc[(orders["difference_days2"]<pd.Timedelta(0)) & (orders["difference_days3"]<pd.Timedelta(0)),"order_approved_at_new"]

    orders["order_delivered_carrier_date_new"]=orders["order_approved_at"]+(orders["order_delivered_customer_date"]-orders["order_approved_at"])/2

    orders.loc[orders["difference_days2"]<pd.Timedelta(0),"order_delivered_carrier_date"]=orders.loc[orders["difference_days2"]<pd.Timedelta(0),"order_delivered_carrier_date_new"]

    orders["order_delivered_carrier_date_new"]=orders["order_approved_at"]+(orders["order_delivered_customer_date"]-orders["order_approved_at"])/2

    orders.loc[orders["difference_days4"]<pd.Timedelta(0),"order_delivered_carrier_date"]=orders.loc[orders["difference_days4"]<pd.Timedelta(0),"order_delivered_carrier_date_new"]

    orders["order_delivered_carrier_date_new"]=orders["order_approved_at"]+(orders["order_delivered_customer_date"]-orders["order_approved_at"])/2
    orders.loc[(orders["order_status"]=="delivered") & (orders["order_delivered_carrier_date"].isnull()),"order_delivered_carrier_date"]=orders.loc[(orders["order_status"]=="delivered") & (orders["order_delivered_carrier_date"].isnull()),"order_delivered_carrier_date_new"]

    orders.loc[(orders["order_status"]=="delivered") & (orders["order_delivered_carrier_date"].isnull()),"order_status"]="approved"

    orders["order_approved_at_new"]=orders["order_purchase_timestamp"]+(orders["order_delivered_carrier_date"]-orders["order_purchase_timestamp"])/2
    orders.loc[(orders["order_status"]=="delivered") & (orders["order_approved_at"].isnull()),"order_approved_at"]=orders.loc[(orders["order_status"]=="delivered") & (orders["order_approved_at"].isnull()),"order_approved_at_new"]

    orders.loc[(orders["order_status"]=="delivered")&(orders["order_delivered_customer_date"].isnull()),"order_status"]="shipped"

    orders.drop(columns=["difference_days1","difference_days2","difference_days3","difference_days4","difference_days5","order_approved_at_new","order_delivered_carrier_date_new"],inplace=True)

    dftotalordercost=payments.groupby(['order_id']).sum()
    dftotalordercost=dftotalordercost.drop(columns=["payment_installments"])
    dftotalordercost.rename(columns={"payment_value":"total_order_cost"},inplace=True)
   
    orders = orders.merge(dftotalordercost[['total_order_cost']], on='order_id', how='outer')    

    return orders


# Payments

def etl_payments():

    payments=payments_inc.copy()

    payments.drop(columns=["payment_sequential"],axis= 1, inplace=True)

    return payments


#Reviews

def etl_reviews():

    reviews=reviews_inc.copy()

    reviews["review_creation_date"]=pd.to_datetime(reviews["review_creation_date"],format="%Y-%m-%d %H:%M:%S")
    reviews["review_answer_timestamp"]=pd.to_datetime(reviews["review_answer_timestamp"],format="%Y-%m-%d %H:%M:%S")

    reviews["review_comment_title"].fillna("SIN TITULO",inplace=True)
    reviews["review_comment_message"].fillna("SIN COMENTARIOS",inplace=True)

    return reviews

# Products

def etl_products():

    products=products_inc.copy()

    products.drop(columns=["product_name_lenght","product_description_lenght","product_weight_g","product_length_cm","product_height_cm","product_width_cm"],axis=1,inplace=True)
    products["product_photos_qty"].fillna(0.0,inplace=True)
    products["product_photos_qty"] = products["product_photos_qty"] .astype("int")
    products["product_category_name"]=products["product_category_name"].str.replace("_"," ")
    products["product_category_name"]=products["product_category_name"].fillna("outras")

    return products

# Items

def etl_items():

    items=items_inc.copy()

    items["shipping_limit_date"]=pd.to_datetime(items["shipping_limit_date"],format="%Y-%m-%d %H:%M:%S")

    return items

In [39]:
#incremental despues de ETL
product_cat_name_in=etl_product_cat()
geolocation_in=etl_geolocation()
marketing_in=etl_marketing()
sellers_in=etl_sellers()
closed_deals_in=etl_closed_deals()
customers_in=etl_customers()
orders_in=etl_orders()
payments_in=etl_payments()
reviews_in=etl_reviews()
products_in=etl_products()
items_in=etl_items()

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_6316\2038168649.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  product_cat_name=product_cat_name.append({"product_category_name" : "pc_gamer" , "product_category_name_english" : "pc_gamer"} , ignore_index=True)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_6316\2038168649.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  product_cat_name=product_cat_name.append({"product_category_name" : "portateis_cozinha_e_preparadores_de_alimentos" , "product_category_name_english" : "kitchen_and_food_preparation_racks"} , ignore_index=True)

In [8]:
product_cat_name_aux=pd.merge(left=product_cat_name_ac,right=product_cat_name_in,on='product_category_name',how='outer')
product_cat_name_aux=pd.merge(left=product_cat_name_aux,right=products_in[['product_category_name']].drop_duplicates(),on='product_category_name',how='outer')
product_cat_name_aux["UPDATE"]="NO"
product_cat_name_aux["INSERT"]="NO"

In [9]:
product_cat_name_aux.loc[(product_cat_name_aux["product_category_name_english_x"]!=product_cat_name_aux["product_category_name_english_y"]) &(product_cat_name_aux.index<=product_cat_name_ac.count()[0]-1),"UPDATE"]="SI"
product_cat_name_aux.loc[product_cat_name_aux.index>product_cat_name_ac.count()[0]-1,"INSERT"]="SI"

In [12]:
# Creación del cursor
cur = conn.cursor()
updateindex=list(product_cat_name_aux[product_cat_name_aux["UPDATE"]=="SI"].index)
for i in updateindex:
    cur.execute("UPDATE product_category_name_translation \
    SET product_category_name_english = '"+str(product_cat_name_aux.loc[i,"product_category_name_english_y"])+"' \
    WHERE product_category_name = '"+str(product_cat_name_aux.loc[i,"product_category_name"])+"'\
    ")
conn.commit()
cur.close()
# Creación del cursor
cur = conn.cursor()
insertindex=list(product_cat_name_aux[product_cat_name_aux["INSERT"]=="SI"].index)
for i in insertindex:
    cur.execute("INSERT INTO product_category_name_translation( \
	 product_category_name, product_category_name_english) \
	VALUES ('"+str(product_cat_name_aux.loc[i,"product_category_name"])+"'\
	,'"+str(product_cat_name_aux.loc[i,"product_category_name_english_y"])+"'\
	)")
conn.commit()
cur.close()

In [13]:
marketing_aux=pd.merge(left=marketing_ac,right=marketing_in,on='mql_id',how='outer')
marketing_aux=pd.merge(left=marketing_aux,right=closed_deals_in[['mql_id']].drop_duplicates(),on='mql_id',how='outer')
marketing_aux["UPDATE"]="NO"
marketing_aux["INSERT"]="NO"

In [14]:
marketing_aux.loc[((marketing_aux["first_contact_date_x"]!=marketing_aux["first_contact_date_y"]) |(marketing_aux["origin_x"]!=marketing_aux["origin_y"])) &(marketing_aux.index<=marketing_ac.count()[0]-1),"UPDATE"]="SI"
marketing_aux.loc[marketing_aux.index>marketing_ac.count()[0]-1,"INSERT"]="SI"

In [15]:
# Creación del cursor,Update
cur = conn.cursor()
updateindex=list(marketing_aux[marketing_aux["UPDATE"]=="SI"].index)
for i in updateindex:
    cur.execute("UPDATE marketing_qualified_leads \
    SET first_contact_date = '"+str(marketing_aux.loc[i,"first_contact_date_y"])+"'\
    ,origin = '"+str(marketing_aux.loc[i,"origin_y"])+"' \
    WHERE mql_id = '"+str(marketing_aux.loc[i,"mql_id"])+"'\
    ")
conn.commit()
cur.close()
# Creación del cursor,INSERT
cur = conn.cursor()
insertindex=list(marketing_aux[marketing_aux["INSERT"]=="SI"].index)
for i in insertindex:
    cur.execute("INSERT INTO marketing_qualified_leads( \
	 mql_id, first_contact_date,origin) \
	VALUES ('"+str(marketing_aux.loc[i,"mql_id"])+"'\
    ,'"+str(marketing_aux.loc[i,"first_contact_date_y"])+"'\
    ,'"+str(marketing_aux.loc[i,"origin_y"])+"'\
    )")
conn.commit()
cur.close()

In [50]:
sellers_aux=pd.merge(left=sellers_ac,right=sellers_in,on='seller_id',how='outer')
sellers_aux=pd.merge(left=sellers_aux,right=closed_deals_in[['seller_id']].drop_duplicates(),on='seller_id',how='outer')
sellers_aux=pd.merge(left=sellers_aux,right=items_in[['seller_id']].drop_duplicates(),on='seller_id',how='outer')
sellers_aux["UPDATE"]="NO"
sellers_aux["INSERT"]="NO"

In [51]:
sellers_aux.loc[(sellers_aux["seller_zip_code_prefix_x"]!=sellers_aux["seller_zip_code_prefix_y"]) &(sellers_aux.index<=sellers_ac.count()[0]-1)& sellers_aux["seller_zip_code_prefix_x"].notnull() &sellers_aux["seller_zip_code_prefix_y"].notnull(),"UPDATE"]="SI"
sellers_aux.loc[sellers_aux.index>sellers_ac.count()[0]-1,"INSERT"]="SI"

In [53]:
# Creación del cursor,Update
cur = conn.cursor()
updateindex=list(sellers_aux[sellers_aux["UPDATE"]=="SI"].index)
for i in updateindex:
    cur.execute("UPDATE olist_sellers \
    SET seller_zip_code_prefix = '"+str(sellers_aux.loc[i,"seller_zip_code_prefix_y"])+"' \
    WHERE seller_id= '"+str(sellers_aux.loc[i,"seller_id"])+"'\
    ")
conn.commit()
cur.close()
# Creación del cursor,INSERT
cur = conn.cursor()
insertindex=list(sellers_aux[sellers_aux["INSERT"]=="SI"].index)
for i in insertindex:
    cur.execute("INSERT INTO olist_sellers( \
	 seller_id,seller_zip_code_prefix ) \
	VALUES ('"+str(sellers_aux.loc[i,"seller_id"])+"'\
    ,'"+str(sellers_aux.loc[i,"seller_zip_code_prefix_y"])+"'\
    )")
conn.commit()
cur.close()

In [66]:
closed_deals_aux=pd.merge(left=closed_deals_ac,right=closed_deals_in,on=['mql_id','seller_id'],how='outer')
closed_deals_aux["UPDATE"]="NO"
closed_deals_aux["INSERT"]="NO"

In [68]:
closed_deals_aux.loc[((closed_deals_aux["won_date_x"]!=closed_deals_aux["won_date_y"]) | (closed_deals_aux["business_segment_x"]!=closed_deals_aux["business_segment_y"])| (closed_deals_aux["lead_type_x"]!=closed_deals_aux["lead_type_y"]))& (closed_deals_aux.index<=closed_deals_ac.count()[0]-1),"UPDATE"]="SI"
closed_deals_aux.loc[closed_deals_aux.index>closed_deals_ac.count()[0]-1,"INSERT"]="SI"

In [ ]:
# Creación del cursor,Update
cur = conn.cursor()
updateindex=list(closed_deals_aux[closed_deals_aux["UPDATE"]=="SI"].index)
for i in updateindex:
    cur.execute("UPDATE closed_deals \
    SET won_date = '"+str(closed_deals_aux.loc[i,"won_date_y"])+"' \
    ,business_segment = '"+str(closed_deals_aux.loc[i,"business_segment_y"])+"' \
    ,lead_type = '"+str(closed_deals_aux.loc[i,"lead_type_y"])+"' \
    WHERE mql_id= '"+str(closed_deals_aux.loc[i,"mql_id"])+"'\
    ")
conn.commit()
cur.close()
# Creación del cursor,INSERT
cur = conn.cursor()
insertindex=list(closed_deals_aux[closed_deals_aux["INSERT"]=="SI"].index)
for i in insertindex:
    cur.execute("INSERT INTO closed_deals( \
	 mql_id,seller_id,won_date,business_segment,lead_type) \
	VALUES ('"+str(closed_deals_aux.loc[i,"mql_id"])+"'\
    ,'"+str(closed_deals_aux.loc[i,"seller_id"])+"'\
    ,'"+str(closed_deals_aux.loc[i,"won_date_y"])+"'\
    ,'"+str(closed_deals_aux.loc[i,"business_segment_y"])+"' \
    ,'"+str(closed_deals_aux.loc[i,"lead_type_y"])+"' \
    )")
conn.commit()
cur.close()

In [70]:
customers_aux=pd.merge(left=customers_ac,right=customers_in,on='customer_id',how='outer')
customers_aux=pd.merge(left=customers_aux,right=orders_in[['customer_id']].drop_duplicates(),on='customer_id',how='outer')

customers_aux["UPDATE"]="NO"
customers_aux["INSERT"]="NO"

In [74]:
customers_aux.loc[((customers_aux["customer_unique_id_x"]!=customers_aux["customer_unique_id_y"]) | (customers_aux["customer_zip_code_prefix_x"]!=customers_aux["customer_zip_code_prefix_y"]))& (customers_aux.index<=customers_ac.count()[0]-1),"UPDATE"]="SI"
customers_aux.loc[customers_aux.index>customers_ac.count()[0]-1,"INSERT"]="SI"

In [ ]:
# Creación del cursor,Update
cur = conn.cursor()
updateindex=list(customers_aux[customers_aux["UPDATE"]=="SI"].index)
for i in updateindex:
    cur.execute("UPDATE customers \
    SET customer_unique_id = '"+str(customers_aux.loc[i,"customer_unique_id_y"])+"'\
    ,customer_zip_code_prefix = '"+str(customers_aux.loc[i,"customer_zip_code_prefix_y"])+"' \
    WHERE customer_id = '"+str(customers_aux.loc[i,"customer_id"])+"'\
    ")
conn.commit()
cur.close()
# Creación del cursor,INSERT
cur = conn.cursor()
insertindex=list(customers_aux[customers_aux["INSERT"]=="SI"].index)
for i in insertindex:
    cur.execute("INSERT INTO customers( \
	 customer_id, customer_unique_id,customer_zip_code_prefix) \
	VALUES ('"+str(customers_aux.loc[i,"customer_id"])+"'\
    ,'"+str(customers_aux.loc[i,"customer_unique_id_y"])+"'\
    ,'"+str(customers_aux.loc[i,"customer_zip_code_prefix_y"])+"'\
    )")
conn.commit()
cur.close()

In [54]:
orders_aux=pd.merge(left=orders_ac,right=orders_in,on='order_id',how='outer')
orders_aux=pd.merge(left=orders_aux,right=payments_in[['order_id']].drop_duplicates(),on='order_id',how='outer')
orders_aux=pd.merge(left=orders_aux,right=reviews_in[['order_id']].drop_duplicates(),on='order_id',how='outer')
orders_aux=pd.merge(left=orders_aux,right=items_in[['order_id']].drop_duplicates(),on='order_id',how='outer')
orders_aux["UPDATE"]="NO"
orders_aux["INSERT"]="NO"

In [64]:
orders_aux["order_purchase_timestamp_x"]!=orders_aux["order_purchase_timestamp_y"]

0        True
1        True
2        True
3        True
4        True
         ...
99436    True
99437    True
99438    True
99439    True
99440    True
Length: 99441, dtype: bool

In [55]:
orders_aux.loc[((orders_aux["customer_id_x"]!=orders_aux["customer_id_y"]) | (orders_aux["order_status_x"]!=orders_aux["order_status_y"])|(orders_aux["order_purchase_timestamp_x"]!=orders_aux["order_purchase_timestamp_y"])|(orders_aux["order_approved_at_x"]!=orders_aux["order_approved_at_y"])|(orders_aux["order_delivered_carrier_date_x"]!=orders_aux["order_delivered_carrier_date_y"])|(orders_aux["order_delivered_customer_date_x"]!=orders_aux["order_delivered_customer_date_y"])|(orders_aux["order_estimated_delivery_date_x"]!=orders_aux["order_estimated_delivery_date_y"])|(orders_aux["total_order_cost_x"]!=orders_aux["total_order_cost_y"]))& (orders_aux.index<=orders_ac.count()[0]-1),"UPDATE"]="SI"
orders_aux.loc[orders_aux.index>orders_ac.count()[0]-1,"INSERT"]="SI"

In [ ]:
# Creación del cursor,Update
cur = conn.cursor()
updateindex=list(orders_aux[orders_aux["UPDATE"]=="SI"].index)
for i in updateindex:
    cur.execute("UPDATE orders \
    SET customer_id = '"+str(orders_aux.loc[i,"customer_id_y"])+"'\
    ,order_status = '"+str(orders_aux.loc[i,"order_status_y"])+"' \
    ,order_purchase_timestamp = '"+str(orders_aux.loc[i,"order_purchase_timestamp_y"])+"' \
    ,order_approved_at = "+str(orders_aux.loc[i,"order_approved_at_y"])+"' \
    ,order_delivered_carrier_date = '"+str(orders_aux.loc[i,"order_delivered_carrier_date_y"])+"' \
    ,order_delivered_customer_date = '"+str(orders_aux.loc[i,"order_delivered_customer_date_y"])+"' \
    ,order_estimated_delivery_date = '"+str(orders_aux.loc[i,"order_estimated_delivery_date_y"])+"' \
    ,total_order_cost = '"+str(orders_aux.loc[i,"total_order_cost_y"])+"' \
    WHERE order_id = '"+str(orders_aux.loc[i,"order_id"])+"'\
    ")
conn.commit()
cur.close()
# Creación del cursor,INSERT
cur = conn.cursor()
insertindex=list(orders_aux[orders_aux["INSERT"]=="SI"].index)
for i in insertindex:
    cur.execute("INSERT INTO orders( \
	 order_id, customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_order_cost) \
	VALUES ('"+str(orders_aux.loc[i,"order_id"])+"'\
    ,'"+str(orders_aux.loc[i,"customer_id_y"])+"'\
    ,'"+str(orders_aux.loc[i,"order_status_y"])+"'\
    ,'"+str(orders_aux.loc[i,"order_purchase_timestamp_y"])+"'\
    ,'"+str(orders_aux.loc[i,"order_approved_at_y"])+"'\
    ,'"+str(orders_aux.loc[i,"order_delivered_carrier_date_y"])+"'\
    ,'"+str(orders_aux.loc[i,"order_delivered_customer_date_y"])+"'\
    ,'"+str(orders_aux.loc[i,"order_estimated_delivery_date_y"])+"'\
    ,'"+str(orders_aux.loc[i,"total_order_cost_y"])+"'\
    )")
conn.commit()
cur.close()

In [92]:
reviews_aux=pd.merge(left=reviews_ac,right=reviews_in,on=['review_id','order_id'],how='outer')
reviews_aux["UPDATE"]="NO"
reviews_aux["INSERT"]="NO"

In [93]:
reviews_aux.tail()

,review_unique_id,review_id,order_id,review_score_x,review_comment_title_x,review_comment_message_x,review_creation_date_x,review_answer_timestamp_x,review_score_y,review_comment_title_y,review_comment_message_y,review_creation_date_y,review_answer_timestamp_y,UPDATE,INSERT
99219,99220,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,SIN TITULO,SIN COMENTARIOS,2018-07-07,2018-07-14,5,SIN TITULO,SIN COMENTARIOS,2018-07-07,2018-07-14 17:18:30,NO,NO
99220,99221,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,SIN TITULO,SIN COMENTARIOS,2017-12-09,2017-12-11,5,SIN TITULO,SIN COMENTARIOS,2017-12-09,2017-12-11 20:06:42,NO,NO
99221,99222,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,SIN TITULO,"Excelente mochila, entrega super rápida. Super...",2018-03-22,2018-03-23,5,SIN TITULO,"Excelente mochila, entrega super rápida. Super...",2018-03-22,2018-03-23 09:10:43,NO,NO
99222,99223,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,SIN TITULO,SIN COMENTARIOS,2018-07-01,2018-07-02,4,SIN TITULO,SIN COMENTARIOS,2018-07-01,2018-07-02 12:59:13,NO,NO
99223,99224,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,SIN TITULO,"meu produto chegou e ja tenho que devolver, po...",2017-07-03,2017-07-03,1,SIN TITULO,"meu produto chegou e ja tenho que devolver, po...",2017-07-03,2017-07-03 21:01:49,NO,NO

In [94]:
reviews_aux.loc[((reviews_aux["review_score_x"]!=reviews_aux["review_score_y"]) | (reviews_aux["review_comment_title_x"]!=reviews_aux["review_comment_title_y"])| (reviews_aux["review_comment_message_x"]!=reviews_aux["review_comment_message_y"])| (reviews_aux["review_creation_date_x"]!=reviews_aux["review_creation_date_y"])| (reviews_aux["review_answer_timestamp_x"]!=reviews_aux["review_answer_timestamp_y"]))& (reviews_aux.index<=reviews_ac.count()[0]-1),"UPDATE"]="SI"
reviews_aux.loc[reviews_aux.index>reviews_ac.count()[0]-1,"INSERT"]="SI"

In [ ]:
# Creación del cursor,Update
cur = conn.cursor()
updateindex=list(reviews_aux[reviews_aux["UPDATE"]=="SI"].index)
for i in updateindex:
    cur.execute("UPDATE order_reviews \
    SET review_score = '"+str(reviews_aux.loc[i,"review_score_y"])+"' \
    ,review_comment_title = '"+str(reviews_aux.loc[i,"review_comment_title_y"])+"' \
    ,review_comment_message = '"+str(reviews_aux.loc[i,"review_comment_message_y"])+"' \
    ,review_creation_date = '"+str(reviews_aux.loc[i,"review_creation_date_y"])+"' \
    ,review_answer_timestamp = '"+str(reviews_aux.loc[i,"review_answer_timestamp_y"])+"' \
    WHERE review_unique_id= '"+str(reviews_aux.loc[i,"review_unique_id"])+"'\
    ")
conn.commit()
cur.close()
# Creación del cursor,INSERT
cur = conn.cursor()
insertindex=list(reviews_aux[reviews_aux["INSERT"]=="SI"].index)
for i in insertindex:
    cur.execute("INSERT INTO order_reviews( \
	 review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp) \
	VALUES ('"+str(reviews_aux.loc[i,"review_id"])+"'\
    ,'"+str(reviews_aux.loc[i,"order_id"])+"'\
    ,'"+str(reviews_aux.loc[i,"review_score_y"])+"'\
    ,'"+str(reviews_aux.loc[i,"review_comment_title_y"])+"' \
    ,'"+str(reviews_aux.loc[i,"review_comment_message_y"])+"' \
    ,'"+str(reviews_aux.loc[i,"review_creation_date_y"])+"' \
    ,'"+str(reviews_aux.loc[i,"review_answer_timestamp_y"])+"' \
    )")
conn.commit()
cur.close()

In [95]:
products_aux=pd.merge(left=products_ac,right=products_in,on='product_id',how='outer')
products_aux=pd.merge(left=products_aux,right=items_in[['product_id']].drop_duplicates(),on='product_id',how='outer')
products_aux["UPDATE"]="NO"
products_aux["INSERT"]="NO"

In [97]:
products_aux.tail()

,product_id,product_category_name_x,product_photos_qty_x,product_category_name_y,product_photos_qty_y,UPDATE,INSERT
32947,bf4538d88321d0fd4412a93c974510e6,construcao ferramentas iluminacao,1.0,construcao ferramentas iluminacao,1,NO,NO
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama mesa banho,1.0,cama mesa banho,1,NO,NO
32949,83808703fc0706a22e264b9d75f04a2e,informatica acessorios,2.0,informatica acessorios,2,NO,NO
32950,106392145fca363410d287a815be6de4,cama mesa banho,1.0,cama mesa banho,1,NO,NO
32951,106392145fca363410d287a815be6de4f,NaN,NaN,Crash bandicoot port,1,NO,NO

In [98]:
products_aux.loc[((products_aux["product_category_name_x"]!=products_aux["product_category_name_y"])|(products_aux["product_photos_qty_x"]!=products_aux["product_photos_qty_y"])) &(products_aux.index<=products_ac.count()[0]-1),"UPDATE"]="SI"
products_aux.loc[products_aux.index>products_ac.count()[0]-1,"INSERT"]="SI"

In [ ]:
# Creación del cursor,Update
cur = conn.cursor()
updateindex=list(products_aux[products_aux["UPDATE"]=="SI"].index)
for i in updateindex:
    cur.execute("UPDATE products \
    SET product_category_name = '"+str(products_aux.loc[i,"product_category_name_y"])+"' \
    ,product_photos_qty = '"+str(products_aux.loc[i,"product_photos_qty_y"])+"' \
    WHERE product_id= '"+str(products_aux.loc[i,"product_id"])+"'\
    ")
conn.commit()
cur.close()
# Creación del cursor,INSERT
cur = conn.cursor()
insertindex=list(products_aux[products_aux["INSERT"]=="SI"].index)
for i in insertindex:
    cur.execute("INSERT INTO products( \
	 product_id,product_category_name,product_photos_qty ) \
	VALUES ('"+str(products_aux.loc[i,"product_id"])+"'\
    ,'"+str(products_aux.loc[i,"product_category_name_y"])+"'\
    ,'"+str(products_aux.loc[i,"product_photos_qty_y"])+"'\
    )")
conn.commit()
cur.close()

In [110]:
items_aux=pd.merge(left=items_ac,right=items_in,on=['order_id','order_item_id','product_id','seller_id'],how='outer')
items_aux["UPDATE"]="NO"
items_aux["INSERT"]="NO"

In [112]:
items_aux.loc[((items_aux["shipping_limit_date_x"]!=items_aux["shipping_limit_date_y"])| (items_aux["price_x"]!=items_aux["price_y"])| (items_aux["freight_value_x"]!=items_aux["freight_value_y"]))& (items_aux.index<=items_ac.count()[0]-1),"UPDATE"]="SI"
items_aux.loc[items_aux.index>items_ac.count()[0]-1,"INSERT"]="SI"

In [113]:
items_aux.tail()

,order_unique_id,order_id,order_item_id,product_id,seller_id,shipping_limit_date_x,price_x,freight_value_x,shipping_limit_date_y,price_y,freight_value_y,UPDATE,INSERT
112645,112646,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02,299.99,43.41,2018-05-02 04:11:01,299.99,43.41,SI,NO
112646,112647,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20,350.00,36.53,2018-07-20 04:31:48,350.00,36.53,SI,NO
112647,112648,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30,99.90,16.95,2017-10-30 17:14:25,99.90,16.95,SI,NO
112648,112649,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21,55.99,8.72,2017-08-21 00:04:32,55.99,8.72,SI,NO
112649,112650,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12,43.00,12.79,2018-06-12 17:10:13,43.00,12.79,SI,NO

In [ ]:
# Creación del cursor,Update
cur = conn.cursor()
updateindex=list(items_aux[items_aux["UPDATE"]=="SI"].index)
for i in updateindex:
    cur.execute("UPDATE order_items \
    SET shipping_limit_date = '"+str(items_aux.loc[i,"shipping_limit_date_y"])+"' \
    ,price = '"+str(items_aux.loc[i,"price_y"])+"' \
    ,freight_value = '"+str(items_aux.loc[i,"freight_value_y"])+"' \
    WHERE order_unique_id= '"+str(items_aux.loc[i,"order_unique_id"])+"'\
    ")
conn.commit()
cur.close()
# Creación del cursor,INSERT
cur = conn.cursor()
insertindex=list(items_aux[items_aux["INSERT"]=="SI"].index)
for i in insertindex:
    cur.execute("INSERT INTO order_items( \
	 order_id,order_item_id,product_id,shipping_limit_date,price,freight_value) \
	VALUES ('"+str(items_aux.loc[i,"order_id"])+"'\
    ,'"+str(items_aux.loc[i,"order_item_id"])+"'\
    ,'"+str(items_aux.loc[i,"product_id_y"])+"'\
    ,'"+str(items_aux.loc[i,"shipping_limit_date_y"])+"' \
    ,'"+str(items_aux.loc[i,"price_y"])+"' \
    ,'"+str(items_aux.loc[i,"freight_value_y"])+"' \
    )")
conn.commit()
cur.close()

In [ ]:
conn.close()